// Country, dial-code, currency data for worldwide shipping.
// `hub` = nearest Trackora hub (auto-computed from lat/lon).

export type Country = {
  code: string;
  name: string;
  dial: string;
  currency: string;
  hub: string;
  flag: string;
};

export const COUNTRIES: Country[] = [
  { code: "AF", name: "Afghanistan", dial: "+93", currency: "AFN", hub: "DEL", flag: "🇦🇫" },
  { code: "AL", name: "Albania", dial: "+355", currency: "ALL", hub: "IST", flag: "🇦🇱" },
  { code: "DZ", name: "Algeria", dial: "+213", currency: "DZD", hub: "MAD", flag: "🇩🇿" },
  { code: "AS", name: "American Samoa", dial: "+1684", currency: "USD", hub: "SFO", flag: "🇦🇸" },
  { code: "AD", name: "Andorra", dial: "+376", currency: "EUR", hub: "MAD", flag: "🇦🇩" },
  { code: "AO", name: "Angola", dial: "+244", currency: "AOA", hub: "LOS", flag: "🇦🇴" },
  { code: "AI", name: "Anguilla", dial: "+1264", currency: "XCD", hub: "BOG", flag: "🇦🇮" },
  { code: "AG", name: "Antigua and Barbuda", dial: "+1268", currency: "XCD", hub: "BOG", flag: "🇦🇬" },
  { code: "AR", name: "Argentina", dial: "+54", currency: "ARS", hub: "EZE", flag: "🇦🇷" },
  { code: "AM", name: "Armenia", dial: "+374", currency: "AMD", hub: "IST", flag: "🇦🇲" },
  { code: "AW", name: "Aruba", dial: "+297", currency: "AWG", hub: "BOG", flag: "🇦🇼" },
  { code: "AU", name: "Australia", dial: "+61", currency: "AUD", hub: "SYD", flag: "🇦🇺" },
  { code: "AT", name: "Austria", dial: "+43", currency: "EUR", hub: "FRA", flag: "🇦🇹" },
  { code: "AZ", name: "Azerbaijan", dial: "+994", currency: "AZN", hub: "IST", flag: "🇦🇿" },
  { code: "BS", name: "Bahamas", dial: "+1242", currency: "BSD", hub: "MIA", flag: "🇧🇸" },
  { code: "BH", name: "Bahrain", dial: "+973", currency: "BHD", hub: "DXB", flag: "🇧🇭" },
  { code: "BD", name: "Bangladesh", dial: "+880", currency: "BDT", hub: "DEL", flag: "🇧🇩" },
  { code: "BB", name: "Barbados", dial: "+1246", currency: "BBD", hub: "BOG", flag: "🇧🇧" },
  { code: "BY", name: "Belarus", dial: "+375", currency: "BYN", hub: "SVO", flag: "🇧🇾" },
  { code: "BE", name: "Belgium", dial: "+32", currency: "EUR", hub: "AMS", flag: "🇧🇪" },
  { code: "BZ", name: "Belize", dial: "+501", currency: "BZD", hub: "MEX", flag: "🇧🇿" },
  { code: "BJ", name: "Benin", dial: "+229", currency: "XOF", hub: "LOS", flag: "🇧🇯" },
  { code: "BM", name: "Bermuda", dial: "+1441", currency: "BMD", hub: "JFK", flag: "🇧🇲" },
  { code: "BT", name: "Bhutan", dial: "+975", currency: "BTN", hub: "DEL", flag: "🇧🇹" },
  { code: "BO", name: "Bolivia", dial: "+591", currency: "BOB", hub: "EZE", flag: "🇧🇴" },
  { code: "BA", name: "Bosnia and Herzegovina", dial: "+387", currency: "BAM", hub: "IST", flag: "🇧🇦" },
  { code: "BW", name: "Botswana", dial: "+267", currency: "BWP", hub: "JNB", flag: "🇧🇼" },
  { code: "BR", name: "Brazil", dial: "+55", currency: "BRL", hub: "GRU", flag: "🇧🇷" },
  { code: "BN", name: "Brunei", dial: "+673", currency: "BND", hub: "SIN", flag: "🇧🇳" },
  { code: "BG", name: "Bulgaria", dial: "+359", currency: "BGN", hub: "IST", flag: "🇧🇬" },
  { code: "BF", name: "Burkina Faso", dial: "+226", currency: "XOF", hub: "LOS", flag: "🇧🇫" },
  { code: "BI", name: "Burundi", dial: "+257", currency: "BIF", hub: "JNB", flag: "🇧🇮" },
  { code: "KH", name: "Cambodia", dial: "+855", currency: "KHR", hub: "SIN", flag: "🇰🇭" },
  { code: "CM", name: "Cameroon", dial: "+237", currency: "XAF", hub: "LOS", flag: "🇨🇲" },
  { code: "CA", name: "Canada", dial: "+1", currency: "CAD", hub: "YYZ", flag: "🇨🇦" },
  { code: "CV", name: "Cape Verde", dial: "+238", currency: "CVE", hub: "LOS", flag: "🇨🇻" },
  { code: "KY", name: "Cayman Islands", dial: "+1345", currency: "KYD", hub: "MIA", flag: "🇰🇾" },
  { code: "CF", name: "Central African Republic", dial: "+236", currency: "XAF", hub: "LOS", flag: "🇨🇫" },
  { code: "TD", name: "Chad", dial: "+235", currency: "XAF", hub: "LOS", flag: "🇹🇩" },
  { code: "CL", name: "Chile", dial: "+56", currency: "CLP", hub: "EZE", flag: "🇨🇱" },
  { code: "CN", name: "China", dial: "+86", currency: "CNY", hub: "PEK", flag: "🇨🇳" },
  { code: "CO", name: "Colombia", dial: "+57", currency: "COP", hub: "BOG", flag: "🇨🇴" },
  { code: "KM", name: "Comoros", dial: "+269", currency: "KMF", hub: "JNB", flag: "🇰🇲" },
  { code: "CG", name: "Congo", dial: "+242", currency: "XAF", hub: "LOS", flag: "🇨🇬" },
  { code: "CD", name: "Congo (DRC)", dial: "+243", currency: "CDF", hub: "LOS", flag: "🇨🇩" },
  { code: "CK", name: "Cook Islands", dial: "+682", currency: "NZD", hub: "LAX", flag: "🇨🇰" },
  { code: "CR", name: "Costa Rica", dial: "+506", currency: "CRC", hub: "BOG", flag: "🇨🇷" },
  { code: "CI", name: "Côte d'Ivoire", dial: "+225", currency: "XOF", hub: "LOS", flag: "🇨🇮" },
  { code: "HR", name: "Croatia", dial: "+385", currency: "EUR", hub: "FRA", flag: "🇭🇷" },
  { code: "CU", name: "Cuba", dial: "+53", currency: "CUP", hub: "MIA", flag: "🇨🇺" },
  { code: "CW", name: "Curaçao", dial: "+599", currency: "ANG", hub: "BOG", flag: "🇨🇼" },
  { code: "CY", name: "Cyprus", dial: "+357", currency: "EUR", hub: "CAI", flag: "🇨🇾" },
  { code: "CZ", name: "Czech Republic", dial: "+420", currency: "CZK", hub: "FRA", flag: "🇨🇿" },
  { code: "DK", name: "Denmark", dial: "+45", currency: "DKK", hub: "AMS", flag: "🇩🇰" },
  { code: "DJ", name: "Djibouti", dial: "+253", currency: "DJF", hub: "DXB", flag: "🇩🇯" },
  { code: "DM", name: "Dominica", dial: "+1767", currency: "XCD", hub: "BOG", flag: "🇩🇲" },
  { code: "DO", name: "Dominican Republic", dial: "+1809", currency: "DOP", hub: "MIA", flag: "🇩🇴" },
  { code: "EC", name: "Ecuador", dial: "+593", currency: "USD", hub: "BOG", flag: "🇪🇨" },
  { code: "EG", name: "Egypt", dial: "+20", currency: "EGP", hub: "CAI", flag: "🇪🇬" },
  { code: "SV", name: "El Salvador", dial: "+503", currency: "USD", hub: "MEX", flag: "🇸🇻" },
  { code: "GQ", name: "Equatorial Guinea", dial: "+240", currency: "XAF", hub: "LOS", flag: "🇬🇶" },
  { code: "ER", name: "Eritrea", dial: "+291", currency: "ERN", hub: "CAI", flag: "🇪🇷" },
  { code: "EE", name: "Estonia", dial: "+372", currency: "EUR", hub: "SVO", flag: "🇪🇪" },
  { code: "SZ", name: "Eswatini", dial: "+268", currency: "SZL", hub: "JNB", flag: "🇸🇿" },
  { code: "ET", name: "Ethiopia", dial: "+251", currency: "ETB", hub: "CAI", flag: "🇪🇹" },
  { code: "FJ", name: "Fiji", dial: "+679", currency: "FJD", hub: "AKL", flag: "🇫🇯" },
  { code: "FI", name: "Finland", dial: "+358", currency: "EUR", hub: "SVO", flag: "🇫🇮" },
  { code: "FR", name: "France", dial: "+33", currency: "EUR", hub: "CDG", flag: "🇫🇷" },
  { code: "GF", name: "French Guiana", dial: "+594", currency: "EUR", hub: "BOG", flag: "🇬🇫" },
  { code: "PF", name: "French Polynesia", dial: "+689", currency: "XPF", hub: "LAX", flag: "🇵🇫" },
  { code: "GA", name: "Gabon", dial: "+241", currency: "XAF", hub: "LOS", flag: "🇬🇦" },
  { code: "GM", name: "Gambia", dial: "+220", currency: "GMD", hub: "LOS", flag: "🇬🇲" },
  { code: "GE", name: "Georgia", dial: "+995", currency: "GEL", hub: "IST", flag: "🇬🇪" },
  { code: "DE", name: "Germany", dial: "+49", currency: "EUR", hub: "FRA", flag: "🇩🇪" },
  { code: "GH", name: "Ghana", dial: "+233", currency: "GHS", hub: "LOS", flag: "🇬🇭" },
  { code: "GI", name: "Gibraltar", dial: "+350", currency: "GIP", hub: "MAD", flag: "🇬🇮" },
  { code: "GR", name: "Greece", dial: "+30", currency: "EUR", hub: "IST", flag: "🇬🇷" },
  { code: "GL", name: "Greenland", dial: "+299", currency: "DKK", hub: "YYZ", flag: "🇬🇱" },
  { code: "GD", name: "Grenada", dial: "+1473", currency: "XCD", hub: "BOG", flag: "🇬🇩" },
  { code: "GP", name: "Guadeloupe", dial: "+590", currency: "EUR", hub: "BOG", flag: "🇬🇵" },
  { code: "GU", name: "Guam", dial: "+1671", currency: "USD", hub: "NRT", flag: "🇬🇺" },
  { code: "GT", name: "Guatemala", dial: "+502", currency: "GTQ", hub: "MEX", flag: "🇬🇹" },
  { code: "GN", name: "Guinea", dial: "+224", currency: "GNF", hub: "LOS", flag: "🇬🇳" },
  { code: "GW", name: "Guinea-Bissau", dial: "+245", currency: "XOF", hub: "LOS", flag: "🇬🇼" },
  { code: "GY", name: "Guyana", dial: "+592", currency: "GYD", hub: "BOG", flag: "🇬🇾" },
  { code: "HT", name: "Haiti", dial: "+509", currency: "HTG", hub: "MIA", flag: "🇭🇹" },
  { code: "HN", name: "Honduras", dial: "+504", currency: "HNL", hub: "MEX", flag: "🇭🇳" },
  { code: "HK", name: "Hong Kong", dial: "+852", currency: "HKD", hub: "HKG", flag: "🇭🇰" },
  { code: "HU", name: "Hungary", dial: "+36", currency: "HUF", hub: "FRA", flag: "🇭🇺" },
  { code: "IS", name: "Iceland", dial: "+354", currency: "ISK", hub: "LHR", flag: "🇮🇸" },
  { code: "IN", name: "India", dial: "+91", currency: "INR", hub: "DEL", flag: "🇮🇳" },
  { code: "ID", name: "Indonesia", dial: "+62", currency: "IDR", hub: "SIN", flag: "🇮🇩" },
  { code: "IR", name: "Iran", dial: "+98", currency: "IRR", hub: "DXB", flag: "🇮🇷" },
  { code: "IQ", name: "Iraq", dial: "+964", currency: "IQD", hub: "CAI", flag: "🇮🇶" },
  { code: "IE", name: "Ireland", dial: "+353", currency: "EUR", hub: "LHR", flag: "🇮🇪" },
  { code: "IM", name: "Isle of Man", dial: "+44", currency: "GBP", hub: "LHR", flag: "🇮🇲" },
  { code: "IL", name: "Israel", dial: "+972", currency: "ILS", hub: "CAI", flag: "🇮🇱" },
  { code: "IT", name: "Italy", dial: "+39", currency: "EUR", hub: "FRA", flag: "🇮🇹" },
  { code: "JM", name: "Jamaica", dial: "+1876", currency: "JMD", hub: "MIA", flag: "🇯🇲" },
  { code: "JP", name: "Japan", dial: "+81", currency: "JPY", hub: "NRT", flag: "🇯🇵" },
  { code: "JO", name: "Jordan", dial: "+962", currency: "JOD", hub: "CAI", flag: "🇯🇴" },
  { code: "KZ", name: "Kazakhstan", dial: "+7", currency: "KZT", hub: "SVO", flag: "🇰🇿" },
  { code: "KE", name: "Kenya", dial: "+254", currency: "KES", hub: "JNB", flag: "🇰🇪" },
  { code: "KI", name: "Kiribati", dial: "+686", currency: "AUD", hub: "AKL", flag: "🇰🇮" },
  { code: "XK", name: "Kosovo", dial: "+383", currency: "EUR", hub: "IST", flag: "🇽🇰" },
  { code: "KW", name: "Kuwait", dial: "+965", currency: "KWD", hub: "DXB", flag: "🇰🇼" },
  { code: "KG", name: "Kyrgyzstan", dial: "+996", currency: "KGS", hub: "DEL", flag: "🇰🇬" },
  { code: "LA", name: "Laos", dial: "+856", currency: "LAK", hub: "HKG", flag: "🇱🇦" },
  { code: "LV", name: "Latvia", dial: "+371", currency: "EUR", hub: "SVO", flag: "🇱🇻" },
  { code: "LB", name: "Lebanon", dial: "+961", currency: "LBP", hub: "CAI", flag: "🇱🇧" },
  { code: "LS", name: "Lesotho", dial: "+266", currency: "LSL", hub: "JNB", flag: "🇱🇸" },
  { code: "LR", name: "Liberia", dial: "+231", currency: "LRD", hub: "LOS", flag: "🇱🇷" },
  { code: "LY", name: "Libya", dial: "+218", currency: "LYD", hub: "IST", flag: "🇱🇾" },
  { code: "LI", name: "Liechtenstein", dial: "+423", currency: "CHF", hub: "FRA", flag: "🇱🇮" },
  { code: "LT", name: "Lithuania", dial: "+370", currency: "EUR", hub: "SVO", flag: "🇱🇹" },
  { code: "LU", name: "Luxembourg", dial: "+352", currency: "EUR", hub: "FRA", flag: "🇱🇺" },
  { code: "MO", name: "Macau", dial: "+853", currency: "MOP", hub: "HKG", flag: "🇲🇴" },
  { code: "MG", name: "Madagascar", dial: "+261", currency: "MGA", hub: "JNB", flag: "🇲🇬" },
  { code: "MW", name: "Malawi", dial: "+265", currency: "MWK", hub: "JNB", flag: "🇲🇼" },
  { code: "MY", name: "Malaysia", dial: "+60", currency: "MYR", hub: "SIN", flag: "🇲🇾" },
  { code: "MV", name: "Maldives", dial: "+960", currency: "MVR", hub: "BOM", flag: "🇲🇻" },
  { code: "ML", name: "Mali", dial: "+223", currency: "XOF", hub: "LOS", flag: "🇲🇱" },
  { code: "MT", name: "Malta", dial: "+356", currency: "EUR", hub: "IST", flag: "🇲🇹" },
  { code: "MH", name: "Marshall Islands", dial: "+692", currency: "USD", hub: "NRT", flag: "🇲🇭" },
  { code: "MQ", name: "Martinique", dial: "+596", currency: "EUR", hub: "BOG", flag: "🇲🇶" },
  { code: "MR", name: "Mauritania", dial: "+222", currency: "MRU", hub: "LOS", flag: "🇲🇷" },
  { code: "MU", name: "Mauritius", dial: "+230", currency: "MUR", hub: "JNB", flag: "🇲🇺" },
  { code: "YT", name: "Mayotte", dial: "+262", currency: "EUR", hub: "JNB", flag: "🇾🇹" },
  { code: "MX", name: "Mexico", dial: "+52", currency: "MXN", hub: "MEX", flag: "🇲🇽" },
  { code: "FM", name: "Micronesia", dial: "+691", currency: "USD", hub: "NRT", flag: "🇫🇲" },
  { code: "MD", name: "Moldova", dial: "+373", currency: "MDL", hub: "IST", flag: "🇲🇩" },
  { code: "MC", name: "Monaco", dial: "+377", currency: "EUR", hub: "CDG", flag: "🇲🇨" },
  { code: "MN", name: "Mongolia", dial: "+976", currency: "MNT", hub: "PEK", flag: "🇲🇳" },
  { code: "ME", name: "Montenegro", dial: "+382", currency: "EUR", hub: "IST", flag: "🇲🇪" },
  { code: "MS", name: "Montserrat", dial: "+1664", currency: "XCD", hub: "BOG", flag: "🇲🇸" },
  { code: "MA", name: "Morocco", dial: "+212", currency: "MAD", hub: "MAD", flag: "🇲🇦" },
  { code: "MZ", name: "Mozambique", dial: "+258", currency: "MZN", hub: "JNB", flag: "🇲🇿" },
  { code: "MM", name: "Myanmar", dial: "+95", currency: "MMK", hub: "SIN", flag: "🇲🇲" },
  { code: "NA", name: "Namibia", dial: "+264", currency: "NAD", hub: "JNB", flag: "🇳🇦" },
  { code: "NR", name: "Nauru", dial: "+674", currency: "AUD", hub: "SYD", flag: "🇳🇷" },
  { code: "NP", name: "Nepal", dial: "+977", currency: "NPR", hub: "DEL", flag: "🇳🇵" },
  { code: "NL", name: "Netherlands", dial: "+31", currency: "EUR", hub: "AMS", flag: "🇳🇱" },
  { code: "NC", name: "New Caledonia", dial: "+687", currency: "XPF", hub: "AKL", flag: "🇳🇨" },
  { code: "NZ", name: "New Zealand", dial: "+64", currency: "NZD", hub: "AKL", flag: "🇳🇿" },
  { code: "NI", name: "Nicaragua", dial: "+505", currency: "NIO", hub: "BOG", flag: "🇳🇮" },
  { code: "NE", name: "Niger", dial: "+227", currency: "XOF", hub: "LOS", flag: "🇳🇪" },
  { code: "NG", name: "Nigeria", dial: "+234", currency: "NGN", hub: "LOS", flag: "🇳🇬" },
  { code: "KP", name: "North Korea", dial: "+850", currency: "KPW", hub: "ICN", flag: "🇰🇵" },
  { code: "MK", name: "North Macedonia", dial: "+389", currency: "MKD", hub: "IST", flag: "🇲🇰" },
  { code: "NO", name: "Norway", dial: "+47", currency: "NOK", hub: "AMS", flag: "🇳🇴" },
  { code: "OM", name: "Oman", dial: "+968", currency: "OMR", hub: "DXB", flag: "🇴🇲" },
  { code: "PK", name: "Pakistan", dial: "+92", currency: "PKR", hub: "DEL", flag: "🇵🇰" },
  { code: "PW", name: "Palau", dial: "+680", currency: "USD", hub: "HKG", flag: "🇵🇼" },
  { code: "PS", name: "Palestine", dial: "+970", currency: "ILS", hub: "CAI", flag: "🇵🇸" },
  { code: "PA", name: "Panama", dial: "+507", currency: "PAB", hub: "BOG", flag: "🇵🇦" },
  { code: "PG", name: "Papua New Guinea", dial: "+675", currency: "PGK", hub: "SYD", flag: "🇵🇬" },
  { code: "PY", name: "Paraguay", dial: "+595", currency: "PYG", hub: "EZE", flag: "🇵🇾" },
  { code: "PE", name: "Peru", dial: "+51", currency: "PEN", hub: "BOG", flag: "🇵🇪" },
  { code: "PH", name: "Philippines", dial: "+63", currency: "PHP", hub: "HKG", flag: "🇵🇭" },
  { code: "PL", name: "Poland", dial: "+48", currency: "PLN", hub: "FRA", flag: "🇵🇱" },
  { code: "PT", name: "Portugal", dial: "+351", currency: "EUR", hub: "MAD", flag: "🇵🇹" },
  { code: "PR", name: "Puerto Rico", dial: "+1787", currency: "USD", hub: "MIA", flag: "🇵🇷" },
  { code: "QA", name: "Qatar", dial: "+974", currency: "QAR", hub: "DXB", flag: "🇶🇦" },
  { code: "RE", name: "Réunion", dial: "+262", currency: "EUR", hub: "JNB", flag: "🇷🇪" },
  { code: "RO", name: "Romania", dial: "+40", currency: "RON", hub: "IST", flag: "🇷🇴" },
  { code: "RU", name: "Russia", dial: "+7", currency: "RUB", hub: "SVO", flag: "🇷🇺" },
  { code: "RW", name: "Rwanda", dial: "+250", currency: "RWF", hub: "JNB", flag: "🇷🇼" },
  { code: "KN", name: "Saint Kitts and Nevis", dial: "+1869", currency: "XCD", hub: "BOG", flag: "🇰🇳" },
  { code: "LC", name: "Saint Lucia", dial: "+1758", currency: "XCD", hub: "BOG", flag: "🇱🇨" },
  { code: "VC", name: "Saint Vincent", dial: "+1784", currency: "XCD", hub: "BOG", flag: "🇻🇨" },
  { code: "WS", name: "Samoa", dial: "+685", currency: "WST", hub: "SFO", flag: "🇼🇸" },
  { code: "SM", name: "San Marino", dial: "+378", currency: "EUR", hub: "FRA", flag: "🇸🇲" },
  { code: "ST", name: "São Tomé and Príncipe", dial: "+239", currency: "STN", hub: "LOS", flag: "🇸🇹" },
  { code: "SA", name: "Saudi Arabia", dial: "+966", currency: "SAR", hub: "DXB", flag: "🇸🇦" },
  { code: "SN", name: "Senegal", dial: "+221", currency: "XOF", hub: "LOS", flag: "🇸🇳" },
  { code: "RS", name: "Serbia", dial: "+381", currency: "RSD", hub: "IST", flag: "🇷🇸" },
  { code: "SC", name: "Seychelles", dial: "+248", currency: "SCR", hub: "BOM", flag: "🇸🇨" },
  { code: "SL", name: "Sierra Leone", dial: "+232", currency: "SLL", hub: "LOS", flag: "🇸🇱" },
  { code: "SG", name: "Singapore", dial: "+65", currency: "SGD", hub: "SIN", flag: "🇸🇬" },
  { code: "SK", name: "Slovakia", dial: "+421", currency: "EUR", hub: "FRA", flag: "🇸🇰" },
  { code: "SI", name: "Slovenia", dial: "+386", currency: "EUR", hub: "FRA", flag: "🇸🇮" },
  { code: "SB", name: "Solomon Islands", dial: "+677", currency: "SBD", hub: "SYD", flag: "🇸🇧" },
  { code: "SO", name: "Somalia", dial: "+252", currency: "SOS", hub: "DXB", flag: "🇸🇴" },
  { code: "ZA", name: "South Africa", dial: "+27", currency: "ZAR", hub: "JNB", flag: "🇿🇦" },
  { code: "KR", name: "South Korea", dial: "+82", currency: "KRW", hub: "ICN", flag: "🇰🇷" },
  { code: "SS", name: "South Sudan", dial: "+211", currency: "SSP", hub: "CAI", flag: "🇸🇸" },
  { code: "ES", name: "Spain", dial: "+34", currency: "EUR", hub: "MAD", flag: "🇪🇸" },
  { code: "LK", name: "Sri Lanka", dial: "+94", currency: "LKR", hub: "BOM", flag: "🇱🇰" },
  { code: "SD", name: "Sudan", dial: "+249", currency: "SDG", hub: "CAI", flag: "🇸🇩" },
  { code: "SR", name: "Suriname", dial: "+597", currency: "SRD", hub: "BOG", flag: "🇸🇷" },
  { code: "SE", name: "Sweden", dial: "+46", currency: "SEK", hub: "AMS", flag: "🇸🇪" },
  { code: "CH", name: "Switzerland", dial: "+41", currency: "CHF", hub: "FRA", flag: "🇨🇭" },
  { code: "SY", name: "Syria", dial: "+963", currency: "SYP", hub: "CAI", flag: "🇸🇾" },
  { code: "TW", name: "Taiwan", dial: "+886", currency: "TWD", hub: "PVG", flag: "🇹🇼" },
  { code: "TJ", name: "Tajikistan", dial: "+992", currency: "TJS", hub: "DEL", flag: "🇹🇯" },
  { code: "TZ", name: "Tanzania", dial: "+255", currency: "TZS", hub: "JNB", flag: "🇹🇿" },
  { code: "TH", name: "Thailand", dial: "+66", currency: "THB", hub: "SIN", flag: "🇹🇭" },
  { code: "TL", name: "Timor-Leste", dial: "+670", currency: "USD", hub: "SIN", flag: "🇹🇱" },
  { code: "TG", name: "Togo", dial: "+228", currency: "XOF", hub: "LOS", flag: "🇹🇬" },
  { code: "TO", name: "Tonga", dial: "+676", currency: "TOP", hub: "SFO", flag: "🇹🇴" },
  { code: "TT", name: "Trinidad and Tobago", dial: "+1868", currency: "TTD", hub: "BOG", flag: "🇹🇹" },
  { code: "TN", name: "Tunisia", dial: "+216", currency: "TND", hub: "MAD", flag: "🇹🇳" },
  { code: "TR", name: "Turkey", dial: "+90", currency: "TRY", hub: "IST", flag: "🇹🇷" },
  { code: "TM", name: "Turkmenistan", dial: "+993", currency: "TMT", hub: "DXB", flag: "🇹🇲" },
  { code: "TC", name: "Turks and Caicos", dial: "+1649", currency: "USD", hub: "MIA", flag: "🇹🇨" },
  { code: "TV", name: "Tuvalu", dial: "+688", currency: "AUD", hub: "AKL", flag: "🇹🇻" },
  { code: "UG", name: "Uganda", dial: "+256", currency: "UGX", hub: "JNB", flag: "🇺🇬" },
  { code: "UA", name: "Ukraine", dial: "+380", currency: "UAH", hub: "SVO", flag: "🇺🇦" },
  { code: "AE", name: "United Arab Emirates", dial: "+971", currency: "AED", hub: "DXB", flag: "🇦🇪" },
  { code: "GB", name: "United Kingdom", dial: "+44", currency: "GBP", hub: "LHR", flag: "🇬🇧" },
  { code: "US", name: "United States", dial: "+1", currency: "USD", hub: "JFK", flag: "🇺🇸" },
  { code: "UY", name: "Uruguay", dial: "+598", currency: "UYU", hub: "EZE", flag: "🇺🇾" },
  { code: "UZ", name: "Uzbekistan", dial: "+998", currency: "UZS", hub: "DEL", flag: "🇺🇿" },
  { code: "VU", name: "Vanuatu", dial: "+678", currency: "VUV", hub: "AKL", flag: "🇻🇺" },
  { code: "VA", name: "Vatican City", dial: "+379", currency: "EUR", hub: "FRA", flag: "🇻🇦" },
  { code: "VE", name: "Venezuela", dial: "+58", currency: "VES", hub: "BOG", flag: "🇻🇪" },
  { code: "VN", name: "Vietnam", dial: "+84", currency: "VND", hub: "HKG", flag: "🇻🇳" },
  { code: "VG", name: "British Virgin Islands", dial: "+1284", currency: "USD", hub: "MIA", flag: "🇻🇬" },
  { code: "VI", name: "US Virgin Islands", dial: "+1340", currency: "USD", hub: "MIA", flag: "🇻🇮" },
  { code: "YE", name: "Yemen", dial: "+967", currency: "YER", hub: "DXB", flag: "🇾🇪" },
  { code: "ZM", name: "Zambia", dial: "+260", currency: "ZMW", hub: "JNB", flag: "🇿🇲" },
  { code: "ZW", name: "Zimbabwe", dial: "+263", currency: "ZWL", hub: "JNB", flag: "🇿🇼" },
];

export const countryByCode = new Map(COUNTRIES.map(c => [c.code, c]));

// Build a deduped currency list from country data + a few extras.
const _currencyMeta: Record<string, { symbol: string; name: string }> = {
  USD:{symbol:"$",name:"US Dollar"}, EUR:{symbol:"€",name:"Euro"}, GBP:{symbol:"£",name:"British Pound"},
  JPY:{symbol:"¥",name:"Japanese Yen"}, CNY:{symbol:"¥",name:"Chinese Yuan"}, INR:{symbol:"₹",name:"Indian Rupee"},
  AED:{symbol:"د.إ",name:"UAE Dirham"}, SAR:{symbol:"﷼",name:"Saudi Riyal"}, AUD:{symbol:"A$",name:"Australian Dollar"},
  NZD:{symbol:"NZ$",name:"New Zealand Dollar"}, CAD:{symbol:"C$",name:"Canadian Dollar"}, MXN:{symbol:"Mex$",name:"Mexican Peso"},
  BRL:{symbol:"R$",name:"Brazilian Real"}, ARS:{symbol:"$",name:"Argentine Peso"}, CLP:{symbol:"$",name:"Chilean Peso"},
  COP:{symbol:"$",name:"Colombian Peso"}, PEN:{symbol:"S/",name:"Peruvian Sol"}, CHF:{symbol:"CHF",name:"Swiss Franc"},
  SEK:{symbol:"kr",name:"Swedish Krona"}, NOK:{symbol:"kr",name:"Norwegian Krone"}, DKK:{symbol:"kr",name:"Danish Krone"},
  PLN:{symbol:"zł",name:"Polish Zloty"}, TRY:{symbol:"₺",name:"Turkish Lira"}, RUB:{symbol:"₽",name:"Russian Ruble"},
  UAH:{symbol:"₴",name:"Ukrainian Hryvnia"}, ZAR:{symbol:"R",name:"South African Rand"}, NGN:{symbol:"₦",name:"Nigerian Naira"},
  KES:{symbol:"KSh",name:"Kenyan Shilling"}, EGP:{symbol:"£",name:"Egyptian Pound"}, MAD:{symbol:"DH",name:"Moroccan Dirham"},
  ILS:{symbol:"₪",name:"Israeli Shekel"}, QAR:{symbol:"QR",name:"Qatari Riyal"}, PKR:{symbol:"₨",name:"Pakistani Rupee"},
  BDT:{symbol:"৳",name:"Bangladeshi Taka"}, LKR:{symbol:"Rs",name:"Sri Lankan Rupee"}, SGD:{symbol:"S$",name:"Singapore Dollar"},
  MYR:{symbol:"RM",name:"Malaysian Ringgit"}, IDR:{symbol:"Rp",name:"Indonesian Rupiah"}, THB:{symbol:"฿",name:"Thai Baht"},
  VND:{symbol:"₫",name:"Vietnamese Dong"}, PHP:{symbol:"₱",name:"Philippine Peso"}, HKD:{symbol:"HK$",name:"Hong Kong Dollar"},
  TWD:{symbol:"NT$",name:"Taiwan Dollar"}, KRW:{symbol:"₩",name:"South Korean Won"},
};

const _seen = new Set<string>();
export const CURRENCIES: { code: string; symbol: string; name: string }[] = [];
// Prioritize the curated list first
for (const code of Object.keys(_currencyMeta)) {
  if (_seen.has(code)) continue;
  _seen.add(code);
  CURRENCIES.push({ code, ...(_currencyMeta[code]) });
}
// Then add any other currencies referenced by countries
for (const c of COUNTRIES) {
  if (_seen.has(c.currency)) continue;
  _seen.add(c.currency);
  CURRENCIES.push({ code: c.currency, symbol: c.currency, name: c.currency });
}

export const currencyByCode = new Map(CURRENCIES.map(c => [c.code, c]));

export function formatMoney(amount: number, code: string): string {
  try {
    return new Intl.NumberFormat(undefined, { style: "currency", currency: code, maximumFractionDigits: 2 }).format(amount);
  } catch {
    const c = currencyByCode.get(code);
    return `${c?.symbol ?? ""}${amount.toLocaleString()} ${code}`;
  }
}

/** Nearest hub for a destination country (auto-routing). Falls back to JFK. */
export function hubForCountry(code: string): string {
  return countryByCode.get(code)?.hub ?? "JFK";
}
